### ISSUE TITLE
Error when loading Clans created before most recent update

### ISSUE THREAD

**Issue by jaxonBunny** [ClanGenOfficial/clangen#1429]
![Clan Generator 5_3_2023 10_52_47 AM](https://user-images.githubusercontent.com/132475811/235957027-462efca6-34f6-497d-951d-44ffa680ff9c.png)
get this error with every clan created before the update

**Comment by archanyhm** [comment]
There's too little information in this issue to really tell you what's going on. Without knowing what version specifically and which "update" is meant specifically, I don't think we can offer any extensive help.

If the issue still persists, feel free to reopen this. Otherwise I'll close this as it's kind of stale after two weeks.
