### ISSUE TITLE
Installing requirements fails on Python 3.12

### ISSUE THREAD

**Issue by larkgz** [ClanGenOfficial/clangen#1852]
`requirements.txt` and `pyproject.toml` request that python < 3.12, but 3.12 has been released as the newest Python version.

**Comment by archanyhm** [comment]
Adjusted the label since the constraint has been added deliberately. Feel free to adjust the constraint to include 3.12 and check for compatibility/stability on that version so we could potentially bump from 3.11 to 3.12 — but since out target versions are 3.8 and 3.11 respectively as of now, everything is working as intended.

**Comment by Thlumyn** [comment]
Closing as no plan to change as of now.
