### ISSUE TITLE
r_c, error2, and missing "Clan" in scar text

### ISSUE THREAD

**Issue by blackkat312** [ClanGenOfficial/clangen#1940]
I sent a cat on a solo border patrol and got gen_border_otherclan_meeting1; it ended up failing and my cat got a claw wound. Upon healing she got scarred and this was the text in her history:

![Bug25](https://github.com/ClanGenOfficial/clangen/assets/134397512/3351c760-90eb-4b6e-8926-b1a125fddabc)

Apologies if I did this wrong, this is my first time making a bug report!

**Comment by dreamboats95** [comment]
was able to reproduce error, traceback/full error message: 

```
scripts.utility - ERROR - utility.py / pronoun_repl / 737 - Failed to find pronoun: PRONOUN/r_c/subject
Traceback (most recent call last):
  File "/Users/samanthawilcoxson/samgen/scripts/utility.py", line 718, in pronoun_repl
    d = cat_pronouns_dict[inner_details[1]][1]
KeyError: 'r_c'
Failed to find pronoun: PRONOUN/r_c/subject
```

this is occurring because r_c is not populating correctly with cat name in the resources/dicts/patrols/general/border.json text but i cant find anything different about this patrol ID's formatting vs. others? dont know enough about the codebase to fix this but hope the info helps someone else debug!

Clan name is also not populating correctly (Lightning vs LightningClan) (var is o_c_n)
