### ISSUE TITLE
[ENHANCEMENT] Restrict Guide age when relationships generate upon creation

### ISSUE THREAD

**Issue by thunderingboom** [ClanGenOfficial/clangen#1965]
Mintpaw is the StarClan guide and thus Murkpaw has never met them, so I assume this is a bug with the thoughts?
![2023-12-18](https://github.com/ClanGenOfficial/clangen/assets/149605071/b978dbdc-c948-4d88-bcf0-bf0e075382e6)
![2023-12-18 (1)](https://github.com/ClanGenOfficial/clangen/assets/149605071/167185f7-e160-4138-a5de-a23eecada67a)

**Comment by DeadGirlRisen** [comment]
Murkpaw is a clan founder, and when you turn on the 'enable random relationship values' when creating a clan, it can give them relationship values with the starclan founder. Not a bug to my knowledge.

**Comment by scribblecrumb** [comment]
This could be a good enhancement to make: if random relationship values are generated then we could consider having a check to ensure the starclan guide has not been dead for so long that it's impossible to have met the living cats?

**Comment by rustykitty** [comment]
@scribblecrumb 
Scribble, I feel like this shouldn't be happening since we already have a check in the code preventing relationship values from being generated (I think?) on [line 2667 of scripts/cat/cats.py](https://github.com/ClanGenOfficial/clangen/blob/development/scripts/cat/cats.py#L2667), since that function is called upon Clan creation.
Unless I am missing something?

**Comment by scribblecrumb** [comment]
hm interesting, you're right.  Perhaps this got patched at some point?  This is a pretty old Issue, so it's possible someone did a quick fix instead of creating an age check.  Guides definitely used to generate with relationships.  We can leave it as is for now or you can look into changing it to allow guides to generate relationships, but with an age check to ensure nothing impossible is happening.

**Comment by rustykitty** [comment]
Sure, I'll look into it.
