### ISSUE TITLE
Grandparent/Grandkit mates

### ISSUE THREAD

**Issue by ReigningMonarch** [ClanGenOfficial/clangen#2053]
A player for Lifegen had "allow first cousins to be mates" on. A grandparent and grandkit were able to become mates.

**Comment by ReigningMonarch** [comment]
![image](https://github.com/ClanGenOfficial/clangen/assets/155932891/0251ae32-165e-4e53-8543-e89681ea258d)
![image](https://github.com/ClanGenOfficial/clangen/assets/155932891/819b1aad-f148-4493-8074-fa656146960f)
![image](https://github.com/ClanGenOfficial/clangen/assets/155932891/72ac7a8a-9d39-408a-afc4-e7912042cb12)

**Comment by Lixxis** [comment]
Do we have any information on what version this was based on and how they ended up as mate, with which event? Is it possible that Snarlstar don't have Bitespeckles as grandkit in the family tree? - this would be my only reason why this happened, otherwise I can't find a reason in the code. 

**INFO:** Usually we don't take issues/bugs from mods, due to the fact we can't verify that the code is 100% the same as in the actual game. Maybe it changed a significant part or the bug was already fixed, but the mod didn't update.

**Comment by ReigningMonarch** [comment]
It was not an event, they were manually made mates for a challenge. Sel has more info on this. Lifegen changed nothing as far as family code goes as far as I know.
