### ISSUE TITLE
cats are able to make murder confessions to kits and newborns

### ISSUE THREAD

**Issue by ZtheCorgi** [ClanGenOfficial/clangen#2131]
this is especially silly with newborns, of course, but basically ever since secret murders and murder reveals were added, i believe cats have been able to confess their crimes to babies. and they love doing it. as funny as it is, this behavior should probably be changed lol

**Comment by RAYTRAC3R** [comment]
Haven't actually encountered this yet, but I feel like this might be interesting for story/roleplay reasons, like the cat is trying to get something off their chest by venting their guilt to someone who no one will listen to and who might not even understand what they're saying. But maybe it should have a decreased chance because it IS kinda silly when you take it at face value without that roleplay aspect lol

**Comment by ZtheCorgi** [comment]
i find it very uncomfortable and awkward, personally, and it's quite frustrating when they confess to a newborn because i only exile cats if they confess to someone who is likely to tell on them. even if the newborn was a couple weeks old and able to hear, they wouldn't remember it. and cats only confess once, so. 

i guess i can see it being a very, very rare event for a cat to confess their crimes to a kitten, if it was actually acknowledged that they're telling this to a child in the event. but i really think they shouldn't be allowed to confess to newborns at all. confessing to kittens just happens far too frequently right now, either way.

**Comment by archanyhm** [comment]
I do agree that lowering the chances of that happening might be a reasonable way forward.

**Comment by scribblecrumb** [comment]
This will be handled by #2256 as we will have increased ability to both control chances of events as well as status/age of involved cats

**Comment by scribblecrumb** [comment]
Fixed in #2256
