### ISSUE TITLE
Crash upon ticking 'Show the Moon that certain history events occurred on' when looking at a murderer's history

### ISSUE THREAD

**Issue by ArtemisEnby** [ClanGenOfficial/clangen#2188]
Just as the title says, when you tick the 'Show the Moon that certain history events occurred on' box in the history tab of a cat who has murdered another cat and has text saying they did so in their history, the game crashes. This is a permanent issue and happens every time you do it. Below is a screenshot of the error message.
Commit #: 4beb03ca62d93fba71b8cde8b57b8738c7e9d458
![Untitled-1](https://github.com/ClanGenOfficial/clangen/assets/128145684/3c2d21fb-497a-44e1-8592-b16fb50aa7e6)

**Comment by Oddlem** [comment]
I hope it's okay for me to post here, but I think I might've figured out this bug!! I think what's happening here is that it's incorrectly interpolating moons in that message as an int and not as a part of the actual string, so it errors out and crashes once you tick that box. 

I'm new to this and I'm not sure if I'm allowed to alter the code, but I think the origin of the bug is in line 1457 in ProfileScreen.py!
