### ISSUE TITLE
[BUG] Game freezes at start

### ISSUE THREAD

**Issue by happy413** [ClanGenOfficial/clangen#2360]
**Type**: Code

**Describe the bug**:
Game opens and instantly freezes/stops responding.

**Grade**: Game-breaking

**Reproduce**: Open the game, in my case through Visual Studio Code

**Commit # or Game Version Number**: 4c1058a4436599cffd1d3e2b223f5491b6493a70

**Additional context**: N/A

**Screenshots**
![image](https://github.com/ClanGenOfficial/clangen/assets/127009701/81bd1777-3653-464c-9c6a-c53a05dca967)

**Comment by CL0WNTH0UGHTS** [comment]
Hello! Do you have all the updated requirements for ClanGen? We recently switched to new requirements for dev version with the updating of a few key packages. This error is caused by that and is not (technically) a bug unless it persists after you've downloaded the new packages. 

We recommend you try and get poetry (which is akin to python or git) so that it automatically updates all packages! You can find more on how to do that under your README.md file.
