### ISSUE TITLE
[CODE] Dark Mode Symbol Sprites

### ISSUE THREAD

**Issue by scribblecrumb** [ClanGenOfficial/clangen#2394]
**Description**
Right now, when displayed on the dark mode BG color, the symbols sprites are rather hard to see.  I would suggest that we adjust the `clan_symbol_sprite()` utility function to allow us to specify if the returned symbol sprite should be adjusted for dark mode. 

As far as the actual sprite itself, it would be nice if we could just have the code modify the image to display at a different hex color (ideally #EFE5CE) instead of needing a whole second spritesheet.

**Comment by j-gynn** [comment]
That's a good idea about single-sprite style. If we're doing that, would suggest changing the existing sprites to greyscale, then applying the tint over top (like Minecraft grass.png does, for example). 

~~You could still do the cream-and-brown thing we have going on, but dark-mode would have to follow the same rules (meaning, you'd have to have an outline that is darker than the main body, which isn't always ideal for dark mode aesthetiques). Unless, of course, anyone wanted the task of separating _every single sprite_ into a base and outline layer... at which point we should just do light and dark sprites since they'd take the same amount of space.~~

**Comment by scribblecrumb** [comment]
> That's a good idea about single-sprite style. If we're doing that, would suggest changing the existing sprites to greyscale, then applying the tint over top (like Minecraft grass.png does, for example). You could still do the cream-and-brown thing we have going on, but dark-mode would have to follow the same rules (meaning, you'd have to have an outline that is darker than the main body, which isn't always ideal for dark mode aesthetiques). Unless, of course, anyone wanted the task of separating _every single sprite_ into a base and outline layer... at which point we should just do light and dark sprites since they'd take the same amount of space.

Maybe I'm misunderstanding something, but the symbol sprites don't have an outline.  They're just one flat color (#574C2D is the hex code) so we wouldn't need separate any layers.  Totally cool if it's easier to just do two spritesheets tho, it's just a little bit of inconvenience when adding symbols to the sheet.

**Comment by j-gynn** [comment]
Nope, not misunderstanding - I just straight-up hallucinated details about them...!
