### ISSUE TITLE
[BUG] Game keeps crashing

### ISSUE THREAD

**Issue by averymoistcrayon** [ClanGenOfficial/clangen#2579]
**Type**: (only select one)
- UI - anything to do with the user interface. maybe a button is not working, or the way some assets are formatted seems to be off. 
- Sprite - an issue with the art in the game
**- Code - general bugs related to how the game runs and responds to you.** 
- Typo - misspellings or incorrect grammar - https://github.com/ClanGenOfficial/clangen/issues/1818

**Describe the bug**
ex.: It's exactly how it's described. The game crashes at random times. Sometimes it can be after half an hour of gameplay, others a mere minute. It primarily happens when I go to click "edit" when on a StarClan cat's page to see what moon events took place.

**Grade**: (only select one)
**- Game-breaking - a bug that makes it impossible to play the game**
- Dire - Still playable, but a major feature is broken
- Important - The bug has a large affect on the gameplay, but is not urgent
- Regular - A typical bug that should be seen to soon, but doesn’t necessarily break the game or inhibit the player
- Non-vital - This bug can easily be ignored and does not have a large impact on play
- Unimportant - This bug has little to no impact on play. 

**Reproduce**

**Patrol ID + Outcome Print (if applicable)**:

**Commit # or Game Version Number**:  v0.11.2

**Additional context**
This has been going on for a little bit now. I'm currently on moon 4000 and generally don't allow cats to fade, which could be a contributing factor. 

**Screenshots**

**Comment by j-gynn** [comment]
This is why fading cats exists - you just have too many kitties! Under the hood, you're probably getting an "out of memory" error. Can you confirm if this issue occurs with a new save or one under 100 moons? Otherwise, this is basically a "you've made your bed, now lie in it" situation - unless a rework of how cats are stored, saved and loaded is developed (which would be a BIGGGG undertaking), this will just happen afaik.

**Comment by carlean101** [comment]
moon 4000 and dont allow cats to fade?? 😭 the problem is that the game is using wayy too much memory from the hundreds of starclan cats you have
solutions:
1. turn on fading, you can turn fading off for certain cats to save your favorite
2. scrap your save and make a new one
3. edit your save file and delete some (many) select cats
4. don't edit sc cats' profiles

**Comment by averymoistcrayon** [comment]
I have an unhealthy attachment to these cats, I have my entire family tree and I like going through it 😭😭
I've started weeding out cats and now let them just fade unless they're really important or pretty. Thanks for tip, since I've started weeding them out we've been moving a lot smoother. I'm planning on retiring this clan soon, I'm gonna be a bit smarter w the new one lol
