### ISSUE TITLE
[CODE] Game crashes when saving after a timeskip

### ISSUE THREAD

**Issue by Altaryu** [ClanGenOfficial/clangen#3312]
### Type of bug

Code - general bugs related to how the game runs and responds to you.

### Description

When I tried saving after timeskipping, the game crashed. I figured this meant that the save didn't go through, but it seemed like everything that happened during the timeskip carried over (injuries, apprentice ceremonies, etc.), but the events were all from Moon 6 (the moon I was on when I started playing tonight).

This is the error:
root - CRITICAL - main.py / log_crash / 118 - Uncaught exception
Traceback (most recent call last):
  File "main.py", line 341, in <module>
  File "scripts\screens\ClanScreen.py", line 65, in handle_event
  File "scripts\game_structure\game_essentials.py", line 516, in save_events
  File "scripts\game_structure\game_essentials.py", line 223, in safe_save
TypeError: CAT OBJECT:18 is not JSON serializable

### Grade

Regular - A typical bug that should be seen to soon, but doesn't necessarily break the game or inhibit the player

### Steps to reproduce the behavior

1. Timeskip 1 moon
2. Attempt to save

### Commit # or Game Version Number

187eae88d7dc2ddc1587a94022c9bb45ad6a7800

### Screenshots

Post-timeskip, but before saving:
![PostTimeskip](https://github.com/user-attachments/assets/319d3967-e36d-45bd-9b31-6da011acc9af)

After the game crashes:
![PostTimeskip_AfterSaving](https://github.com/user-attachments/assets/562dc387-a2bd-435a-8439-ce39e3fd91f6)

**Comment by Altaryu** [comment]
Frick, that first screenshot was on the wrong tab

**Comment by j-gynn** [comment]
Argh, I know why this is happening but I don't have capacity to fix it. The issue is as follows:

In order to make events translatable, the relevant cats have to be passed into it to allow their pronouns to display in them. This makes use of the monkeypatch that uses `event_text_adjust`, as it adds a few features outside of the simple `adjust_text` function. However, `event_text_adjust` **requires** passing in Cat objects, and internally transforms them into the (`cat.name, choice(cat.pronouns)`) format that `adjust_text` needs. Events are saved to `events.json` to display the next time the game loads. However, `Cat` is not JSON serializable, so the game crashes.

A fix would be to rearrange `event_text_adjust` to accept the `(cat.name, cat.pronouns)` arrangement as well as cat objects so that we can just save the necessary data in `events.json`.

An alternative fix would be to make the Cat class JSON serializable, at the cost of significantly bloating the `events.json` file (potentially not a big deal?).

Either would fix the issue. I have a possible preference for the first, but honestly anything would be great as this is a pretty nasty bug.
