### ISSUE TITLE
Won't work

### ISSUE THREAD

**Issue by Locustfang339** [ClanGenOfficial/clangen#438]
you guys know the first black screen right? well, instead of the black screen then the smaller, menu screen, it just gets smaller and stays back. i reset my chrome twice and refreshed the page a million times. what do i do to fix this?

**Comment by Locustfang339** [comment]
it just gets smaller and stays BLACK*

**Comment by keyraven** [comment]
Are you on the web version, found at https://clangen-web.github.io/ ? That version tends to sometimes have trouble loading up saves. I suggest trying Control+F5, which will reload and clear the cache.

**Comment by Locustfang339** [comment]
thanks! I'
ll try that.

**Comment by Locustfang339** [comment]
a small textbox appeared what do i type in it?

**Comment by Locustfang339** [comment]
btw this is what im on : https://clangen-web.github.io

**Comment by Locustfang339** [comment]
i understand you are probably busy and have other things to do, but is there anything i need to do? like a process i need to go through in order to play it again? please answer as fast as possible.sorry for the inconvenience.

**Comment by larkgz** [comment]
Hi, sorry for the delay!

The web version is actually maintained in a [separate repository](https://github.com/Clangen-Web/clangen-web.github.io) by just one person, so reporting the issue here is unlikely to result in a fix.

That being said, I believe that this particular issue with the web version is known. Unfortunately the developer has not found the time to fix the error yet. It’s possible that the game would work if you opened it in an incognito window but I think that further tech support is out of scope for the issues page of this repository. On the Discord (linked in the README) you might be able to find help in the tech support channels.
